version: "3.5"

services:
  horovod_workers:
    image: 200.144.114.144:5000/horovod_base
    command : bash -c "/usr/sbin/sshd -p 12345; sleep infinity"
    environment:
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    networks:
      - horovod_cluster_network
    volumes:
      - /home/invesalius/apps:/apps
    deploy:
      mode: global

networks:
  horovod_cluster_network:
    driver: overlay
    name: horovod_network
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.0/24
